// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//  import 'firebase_options.dart';
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
//  );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgPoSn2yEkTIGiBRo8rxzpm44R50TDolA',
    appId: '1:231575163845:web:1bd13615442b1bdc2071ac',
    messagingSenderId: '231575163845',
    projectId: 'abc-learning-1abb6',
    authDomain: 'abc-learning-1abb6.firebaseapp.com',
    storageBucket: 'abc-learning-1abb6.appspot.com',
    measurementId: 'G-2RTKLG8ELB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6-XEEf6MWxvfhWtI6DVVFhsSceDnDtjw',
    appId: '1:231575163845:android:82cdb1a86e772be52071ac',
    messagingSenderId: '231575163845',
    projectId: 'abc-learning-1abb6',
    storageBucket: 'abc-learning-1abb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfE0nVV439OQ51FMS5hGOrhAjkAzyC7y0',
    appId: '1:231575163845:ios:ac51c74193a500522071ac',
    messagingSenderId: '231575163845',
    projectId: 'abc-learning-1abb6',
    storageBucket: 'abc-learning-1abb6.appspot.com',
    androidClientId:
        '231575163845-343e2og8n3ps6ggg23sgvr6nfs7ugf9t.apps.googleusercontent.com',
    iosClientId:
        '231575163845-g8jps052gemh6u2d2lp8kfdn8tbhlnh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.abcLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfE0nVV439OQ51FMS5hGOrhAjkAzyC7y0',
    appId: '1:231575163845:ios:3358a3cb51eaebd32071ac',
    messagingSenderId: '231575163845',
    projectId: 'abc-learning-1abb6',
    storageBucket: 'abc-learning-1abb6.appspot.com',
    androidClientId:
        '231575163845-343e2og8n3ps6ggg23sgvr6nfs7ugf9t.apps.googleusercontent.com',
    iosClientId:
        '231575163845-s76cclluj25b3biaiel8hbkv280ko9mh.apps.googleusercontent.com',
    iosBundleId: 'com.example.abcLearningApp.RunnerTests',
  );
}
